AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: vaultwarden api
Globals:
    Function:
        Timeout: 10

Parameters:
    CustomDomain:
        Type: String
        Description: Custom Domain
    CertificateArn:
        Type: String
        Description: CertificateArn
    DatabaseUrl:
        Type: String
        Description: DatabaseUrl
Resources:
    VaultwardenApi:
        Type: AWS::Serverless::HttpApi
        Properties:
            Domain:
                CertificateArn: !Ref CertificateArn
                DomainName: !Ref CustomDomain
            StageName: $default
            DefaultRouteSettings:
                ThrottlingBurstLimit: 5
                ThrottlingRateLimit: 3
    VaultwardenLambda:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: 'VaultwardenLambda'
            PackageType: Image
            ImageUri: !Sub '${AWS::AccountId}.dkr.ecr.us-west-2.amazonaws.com/vaultwarden:1.30.1'
            Environment:
                Variables:
                    DATABASE_URL: !Ref DatabaseUrl
                    DB_CONNECTION_RETRIES: 2
                    DOMAIN_ORIGIN:
                    DATA_FOLDER: /tmp/data
                    I_REALLY_WANT_VOLATILE_STORAGE: true
                    WEB_VAULT_ENABLED: false
            Events:
                ApiEvent:
                    Properties:
                        ApiId: !Ref 'VaultwardenApi'
                        Method: ANY
                        Path: /{proxy+}
                    Type: HttpApi